---
title: "LesMiserables - SAND"
author: "Giacomo Victor Massari"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries, warning=FALSE, message=FALSE}
library(readr)
library(igraph)
library(igraphdata)
library(sand)
```


# Upload Data
```{r upload, message=FALSE}
nodes <- read_csv("jean-complete-node.csv")
head(nodes)
summary(nodes)

edges <- read_csv("jean-complete-edge.csv")
head(edges)
summary(edges)
```

## check for NAs
```{r check for NA}
table(is.na(edges))

which(is.na(edges))
edges[1097,]

dim(edges)
edges <- na.omit(edges)
dim(edges)

table(is.na(edges))
```


```{r}
g <- graph_from_data_frame(edges, directed=FALSE)

plot(g, vertex.label=NA)
```

## initial analysis
```{r}
# degree for each node
hist(degree(g))
```

```{r}
hist(graph.strength(g))
```

```{r capo dei capo}
s <- graph.strength(g)
b <- betweenness(g)

plot(s, b)
```
```{r}
ia <- order(b, decreasing=TRUE)


V(g)$role[order(s, decreasing=TRUE)]
```

```{r}
ia <- order(b, decreasing=T)[1]
which.max(b)

name <- names(which.max(b))

name_out <- nodes[nodes$Id == name, ][2, 2]

namename <- name_out$Label

cat('the important actor is',namename,'\n')
```


```{r}
degree_dist <- function(graph) {
  fd <- table(degree(graph))
  d <- as.numeric(names(fd)) + 1 
  list(d = d, fd = fd)
}
```

```{r}
dd <- degree_dist(g)

head(dd$d,20)
head(dd$fd,20)
```
```{r}
with(dd, plot(log(d), log(fd)))
```








